development:
  adapter: postgresql
  encoding: unicode
  database: any_raffle_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter

test:
  adapter: postgresql
  encoding: unicode
  database: any_raffle_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter

production:
  adapter: postgresql
  encoding: unicode
  database: any_raffle_production
  pool: 5
  password:
